"""
This type stub file was generated by pyright.
"""

class ActionDetector:
    def __init__(self, n_actions: int, loop_length: int = ...) -> None:
        ...
    
    def is_repeated(self, action: int) -> bool:
        ...
    


