"""
This type stub file was generated by pyright.
"""

import dgl
from typing import Any, Dict, Optional
from grid2op.Environment import BaseEnv
from pop.configs.architecture import Architecture
from pop.multiagent_system.base_pop import BasePOP

class DPOP(BasePOP):
    def __init__(self, env: BaseEnv, name: str, architecture: Architecture, training: bool, seed: int, checkpoint_dir: Optional[str] = ..., tensorboard_dir: Optional[str] = ..., device: Optional[str] = ...) -> None:
        ...
    
    def get_action(self, graph: dgl.DGLHeteroGraph) -> int:
        ...
    
    def get_state(self: DPOP) -> Dict[str, Any]:
        ...
    
    @staticmethod
    def factory(checkpoint: Dict[str, Any], env: Optional[BaseEnv] = ..., tensorboard_dir: Optional[str] = ..., checkpoint_dir: Optional[str] = ..., name: Optional[str] = ..., training: Optional[bool] = ...) -> DPOP:
        ...
    


