"""
This type stub file was generated by pyright.
"""

from typing import AbstractSet, Iterable, Optional

class FixedSet(AbstractSet):
    def __init__(self, size: int, iterable: Optional[Iterable] = ...) -> None:
        ...
    
    def __contains__(self, x: object) -> bool:
        ...
    
    def __len__(self) -> int:
        ...
    
    def __iter__(self):
        ...
    
    def __str__(self) -> str:
        ...
    
    def add(self, x: object): # -> None:
        ...
    


