[reproducibility]
seed = 0
device = "cpu"

[model]
name = "dpop_rte_1e4"
architecture_path = "../architectures/dpop_small.toml"
data_dir = "../test_data"
checkpoint_dir = "<<model_data_dir>>/pop_runs/checkpoint/<<model_name>>"

[training]
steps = 1e1
train = false
tensorboard_dir = "<<model_data_dir>>/pop_runs/tensorboard/<<model_name>>/"
curriculum = false
reset_decay = true

[evaluation]
episodes = 10
evaluation_dir = "<<model_data_dir>>/evaluation/<<model_name>>"

[loading]
load = true
load_dir = "<<model_checkpoint_dir>>/<<model_name>>.pt"

[environment]
name = "rte_case14_realistic"

[environment.reward]