"""
This type stub file was generated by pyright.
"""

from typing import List, Set

def louvain_communities(G, partition: List[Set[int]], weight=..., resolution=..., threshold=..., seed=..., enable_power_supply_modularity: bool = ..., alpha: float = ..., beta: float = ...): # -> List[Set[int]]:
    ...

def louvain_partitions(G, partition: List[Set[int]], weight=..., resolution=..., threshold=..., seed=..., enable_power_supply_modularity=..., alpha: float = ..., beta: float = ...): # -> Generator[List[Set[int]], None, None]:
    ...

