[pop]
agent_neighbourhood_radius = 1
decentralized = false
fixed_communities = true
epsilon_beta_scheduling = true
agent_type = "uniform"

[agent]
embedding = "egat_architecture_small"
advantage_stream = "advantage_stream_small"
value_stream = "value_stream_small"
learning_rate = 1e-2
learning_frequency = 4
target_network_weight_replace_steps = 500
gamma = 0.99
huber_loss_delta = 1.0
batch_size = 288


[agent.exploration]
max_epsilon = 1.0
min_epsilon = 0.01
epsilon_decay = 200

[agent.replay_memory]
alpha = 0.5
max_beta = 1.0
min_beta = 0.0
beta_decay = 200

[manager]
embedding = "egat_architecture_very_small"
advantage_stream = "advantage_stream_small"
value_stream = "value_stream_small"
learning_rate = 1e-2
learning_frequency = 4
target_network_weight_replace_steps = 500
gamma = 0.99
huber_loss_delta = 1.0
batch_size = 288

[manager.exploration]
max_epsilon = 1.0
min_epsilon = 0.01
epsilon_decay = 200

[manager.replay_memory]
alpha = 0.5
max_beta = 1.0
min_beta = 0.0
beta_decay = 200

[head_manager]
embedding = "gat_architecture_small"
advantage_stream = "advantage_stream_small"
value_stream = "value_stream_small"
learning_rate = 1e-2
learning_frequency = 4
target_network_weight_replace_steps = 500
gamma = 0.99
huber_loss_delta = 1.0
batch_size = 288

[head_manager.exploration]
max_epsilon = 1.0
min_epsilon = 0.01
epsilon_decay = 200

[head_manager.replay_memory]
alpha = 0.5
max_beta = 1.0
min_beta = 0.0
beta_decay = 200


