"""
This type stub file was generated by pyright.
"""

import torch.nn as nn
from typing import Tuple
from torch import Tensor
from dgl import DGLHeteroGraph

class EGATFlatten(nn.Module):
    def __init__(self) -> None:
        ...
    
    def forward(self, g: DGLHeteroGraph, node_embedding: Tensor, edge_embedding: Tensor) -> Tuple[Tensor, Tensor]:
        ...
    


class GATFlatten(nn.Module):
    def __init__(self) -> None:
        ...
    
    def forward(self, g: DGLHeteroGraph, node_embedding: Tensor): # -> Tensor:
        ...
    


class EGATNodeConv(nn.Module):
    def __init__(self, in_feats: int, out_feats: int, bias=..., weight=..., allow_zero_in_degree=...) -> None:
        ...
    
    def forward(self, g: DGLHeteroGraph, node_embedding: Tensor, edge_embedding: Tensor) -> Tensor:
        ...
    


