"""
This type stub file was generated by pyright.
"""

import torch.nn as nn
from typing import Any, Dict, Optional
from dgl import DGLHeteroGraph
from torch import Tensor
from pop.networks.serializable_module import SerializableModule
from pop.configs.network_architecture import NetworkArchitecture

class GCN(nn.Module, SerializableModule):
    def __init__(self, node_features: int, architecture: NetworkArchitecture, name: str, log_dir: Optional[str] = ..., edge_features: Optional[int] = ...) -> None:
        ...
    
    def forward(self, g: DGLHeteroGraph) -> Tensor:
        ...
    
    def get_embedding_dimension(self) -> int:
        ...
    
    def get_state(self) -> Dict[str, Any]:
        ...
    
    @staticmethod
    def factory(checkpoint: Dict[str, Any], **kwargs) -> GCN:
        ...
    


