"""
This type stub file was generated by pyright.
"""

import dgl.nn.pytorch as dgl_nn
from typing import TYPE_CHECKING, Union
from pop.configs.network_architecture import NetworkArchitecture
from pop.networks.gcn import GCN
from networks.dueling_net import DuelingNet

if TYPE_CHECKING:
    ...
def get_network(self: Union[GCN, DuelingNet, InverseNetwork], architecture: NetworkArchitecture, is_graph_network: bool) -> dgl_nn.Sequential:
    ...

