"""
This type stub file was generated by pyright.
"""

import grid2op.Environment
from typing import Union
from configs.run_config import RunConfiguration
from grid2op import Environment
from grid2op.Action import BaseAction
from grid2op.Agent import BaseAgent
from grid2op.Environment import BaseEnv
from grid2op.Reward import RedispReward

class NoActionRedispReward(RedispReward):
    def __init__(self, logger=...) -> None:
        ...
    
    def __call__(self, action: BaseAction, env: Environment, has_error: bool, is_done: bool, is_illegal: bool, is_ambiguous: bool):
        ...
    


def set_experimental_reward(env): # -> None:
    ...

def set_l2rpn_reward(env, alarm: bool = ...): # -> None:
    ...

def set_reward(env, config: RunConfiguration): # -> None:
    ...

def evaluate(config: RunConfiguration, env: Union[grid2op.Environment.Environment, grid2op.Environment.MultiMixEnvironment], agent: BaseAgent, path_save: str, nb_episode: int = ..., nb_process: int = ..., sequential: bool = ...): # -> None:
    ...

def fix_seed(env_train: BaseEnv, env_val: BaseEnv, seed: int = ...): # -> None:
    ...

def main(**kwargs): # -> None:
    ...

p = ...
if __name__ == "__main__":
    args = ...
