"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Optional
from pop.configs.agent_architecture import AgentArchitecture

@dataclass(frozen=True)
class POPArchitecture:
    node_features: int
    edge_features: int
    agent_neighbourhood_radius: int
    decentralized: bool
    epsilon_beta_scheduling: bool
    enable_power_supply_modularity: bool
    manager_history_size: int
    manager_initialization_half_life: int
    agent_type: str
    disabled_action_loops_length: int
    ...


@dataclass(frozen=True)
class Architecture:
    pop: POPArchitecture
    agent: AgentArchitecture
    manager: AgentArchitecture
    head_manager: AgentArchitecture
    def __init__(self, path: Optional[str] = ..., network_architecture_implementation_folder_path: Optional[str] = ..., network_architecture_frame_folder_path: Optional[str] = ..., load_from_dict: Optional[dict] = ...) -> None:
        ...
    


