"""
This type stub file was generated by pyright.
"""

from typing import Dict, Union

def replace_backward_reference(reference_dict: Dict[str, Dict[str, Union[int, bool, float, str]]], value_to_replace: Union[int, float, bool, str], evaluate_expressions: bool) -> Union[int, float, bool, str]:
    ...

def replace_placeholders(implementation_dict: Dict[str, Union[str, Dict[str, Union[int, float, str, bool]]],], frame_dict: Dict[str, Dict[str, str]]) -> Dict[str, Dict[str, Union[int, bool, float, str]]]:
    ...

