"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Dict, Union
from pop.configs.architecture import Architecture
from pop.configs.type_aliases import ParsedTOMLDict

@dataclass(frozen=True)
class Reproducibility:
    seed: int
    device: str
    ...


@dataclass(frozen=True)
class ModelParameters:
    name: str
    architecture: Architecture
    data_dir: str
    checkpoint_dir: str
    def __init__(self, model_dict: Dict[str, Union[int, bool, str, float]]) -> None:
        ...
    


@dataclass(frozen=True)
class TrainingParameters:
    steps: int
    train: bool
    tensorboard_dir: str
    curriculum: bool
    reset_decay: bool
    ...


@dataclass(frozen=True)
class EvaluationParameters:
    episodes: int
    evaluation_dir: str
    generate_grid2viz_data: str
    compute_score: str
    ...


@dataclass(frozen=True)
class LoadingParameters:
    load: bool
    load_dir: str
    ...


@dataclass(frozen=True)
class RewardSpecification:
    reward_components: Dict[str, float]
    ...


@dataclass(frozen=True)
class EnvironmentParameters:
    name: str
    reward: RewardSpecification
    difficulty: Union[int, str]
    def __init__(self, environment_dict: Dict[str, Union[str, bool, int, float, Dict[str, float]]]) -> None:
        ...
    


def replace_all_backward_references(run_config_dict: ParsedTOMLDict): # -> dict[Unknown, Unknown]:
    ...

@dataclass(frozen=True)
class RunConfiguration:
    reproducibility: Reproducibility
    model: ModelParameters
    training: TrainingParameters
    evaluation: EvaluationParameters
    loading: LoadingParameters
    environment: EnvironmentParameters
    def __init__(self, path: str) -> None:
        ...
    


