"""
This type stub file was generated by pyright.
"""

import ray
from typing import Any, Dict, Optional
from dgl import DGLHeteroGraph
from ray import ObjectRef
from torch import Tensor
from pop.agents.base_gcn_agent import BaseGCNAgent
from pop.configs.agent_architecture import AgentArchitecture

@ray.remote(num_cpus=1)
class Manager(BaseGCNAgent):
    def __init__(self, agent_actions: int, node_features: int, architecture: AgentArchitecture, name: str, training: bool, device: str, edge_features: Optional[int] = ...) -> None:
        ...
    
    def get_embedding_size(self) -> int:
        ...
    
    def get_node_embeddings(self, transformed_observation: DGLHeteroGraph) -> Tensor:
        ...
    
    @staticmethod
    def factory(checkpoint: Dict[str, Any], **kwargs) -> ObjectRef:
        ...
    


