"""
This type stub file was generated by pyright.
"""

import networkx as nx
import ray
from typing import Any, Dict, List, Optional, Tuple
from dgl import DGLHeteroGraph
from ray import ObjectRef
from pop.agents.base_gcn_agent import BaseGCNAgent
from pop.configs.agent_architecture import AgentArchitecture

@ray.remote
class RayShallowGCNAgent(BaseGCNAgent):
    def __init__(self, name: str, device: str, agent_actions: Optional[int] = ..., node_features: Optional[int] = ..., edge_features: Optional[int] = ..., architecture: Optional[AgentArchitecture] = ..., training: bool = ...) -> None:
        ...
    
    def get_state(self) -> Dict[str, Any]:
        ...
    
    def get_name(self) -> str:
        ...
    
    @staticmethod
    def factory(checkpoint: Dict[str, Any], **kwargs) -> ObjectRef:
        ...
    
    def take_action(self, transformed_observation: DGLHeteroGraph, mask: List[int] = ...) -> int:
        ...
    
    def step(self, observation: DGLHeteroGraph, action: int, reward: float, next_observation: nx.Graph, done: bool, stop_decay: bool = ...) -> Tuple[None, float]:
        ...
    


