"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Tuple
from configs.agent_architecture import ReplayMemoryParameters

Transition = ...
class ReplayMemory:
    def __init__(self, architecture: ReplayMemoryParameters) -> None:
        ...
    
    def push(self, observation: Any, action: int, next_observation: Any, reward: float, done: bool) -> None:
        ...
    
    def is_empty(self) -> bool:
        ...
    
    def is_full(self) -> bool:
        ...
    
    def update(self): # -> None:
        ...
    
    def sample(self, batch_size: int) -> Tuple[List[int], List[Transition], List[float]]:
        ...
    
    def update_priorities(self, idxs: List[int], priorities: List[float]) -> None:
        ...
    
    def __len__(self) -> int:
        ...
    
    def get_state(self) -> dict:
        ...
    
    def load_state(self, state_dict: dict) -> None:
        ...
    


